#!/bin/bash
set -e

echo ""
echo "*****"
echo "export"
export

echo ""
echo "*****"
echo "java -version"
java -version

echo ""
echo "*****"
echo "javac -version"
javac -version

echo ""
echo "*****"
echo "mvn -version"
mvn -version

echo ""
mvn -B clean install || exit 1
echo ""
