name: App class development
on:
  push:
    branches:
      - main
    paths:
      - "app-class/**"

  workflow_dispatch:

jobs:
  deviceMgmt_develop:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kosdev-code/kos-buildpublish/kos_builder:dockerimage
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
      env:
        KOS_KABTOOL_JAR: "/usr/local/lib/kabtool.jar"
        JAVA_CMD: "java"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ github.event.repository.name }}
          lfs: true

      - name: Build and Publish
        env:
          STUDIO_APIKEY: ${{ secrets.STUDIO_APIKEY }}
        working-directory: ./${{ github.event.repository.name }}
        run: |
          kos_build_handler.sh automation .github/kosbuild-app-class.json
