name: "Build"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  kos_build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kosdev-code/kos-buildpublish/kos_builder:dockerimage
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Build and Publish
        env:
          STUDIO_APIKEY: ${{ secrets.STUDIO_APIKEY }}

        working-directory: ./${{ github.event.repository.name }}
        run: |
          kos_build_handler.sh automation .github/develop-all.json

