name: Kosdev Tutorials - Release Workflow
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  rack_release:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/kosdev-code/kos-buildpublish/kos_builder:dockerimage
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
      env:
        KOS_KABTOOL_JAR: "/usr/local/lib/kabtool.jar"
        JAVA_CMD: "java"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ github.event.repository.name }}
          lfs: true

      - name: Extract Version
        run: |
          echo KOSBUILD_VERSION=${GITHUB_REF#refs/tags/} >> $GITHUB_ENV

      - name: Build and Publish
        env:
          STUDIO_APIKEY: ${{ secrets.STUDIO_APIKEY }}
        working-directory: ./${{ github.event.repository.name }}
        run: |
          export KOS_STD_VERSION=${KOSBUILD_VERSION} 
          export KOSBUILD_VERSION=${KOSBUILD_VERSION}
          kos_build_handler.sh automation .github/release.json
